### ISSUE TITLE
Add support for Java Gradle and Golang

### ISSUE THREAD

**Issue by Alok650** [anakzr/backstage-plugin-library-check#6]
### Description

Hi
I am planning to intergrate this plugin with my service catalog, but it would be useful if we have support for java gradle based projects aswell as golang (go.mod)

### Problem Statement/Justification

Extending to java grade and go.mod

### Proposed Solution or API

For gradle, we can check the modules. for golang, lets check the go.mod

**Comment by accezar** [comment]
Hi @Alok650, thank you for your interest.

I have an upcoming version supporting Pom and Gradle files. Go is the next task on the list.

Stay tuned and please report any issues.

**Comment by accezar** [comment]
@rocha-bruno @Alok650 Java support is now available 🚀

**Comment by rocha-bruno** [comment]
> @rocha-bruno @Alok650 Java support is now available 🚀

Thank you for this awesome work!
We will check and give you feedback if we find areas of possible improvements or ideas.

**Comment by moonfruit85** [comment]
@accezar thank you for adding this functionality. I believe I have found a minor bug though.

In the `PomXmlHandler` the list of dependencies are determined by `result.project.dependencyManagement.dependencies.dependency`. However, not all Java projects use the `dependencyManagement` section, which can result in null pointer issues.

Instead, I would suggest something like `result.project.dependencyManagement?.dependencies.dependency` to check if `dependencyManagement` is defined, and then adding a second check on `result.project.dependencies.dependency`. If one/both are populated, their contents can be processed by a shared function to populate the `libraries` object that is returned.

**Comment by accezar** [comment]
Thank you @moonfruit85 Can you please open an issue with details and prints if possible? I will take a look.
